routes/web.php
<?php

use App\Http\Controllers\Dashboard\AgentController;
use App\Http\Controllers\Dashboard\ApplicationController;
use App\Http\Controllers\Dashboard\AppointmentController;
use App\Http\Controllers\Dashboard\BranchController;
use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\CityController;
use App\Http\Controllers\Dashboard\ClientController;
use App\Http\Controllers\Dashboard\ContactController;
use App\Http\Controllers\Dashboard\CountryController;
use App\Http\Controllers\Dashboard\EnquryController;
use App\Http\Controllers\Dashboard\OfficeCheckinController;
use App\Http\Controllers\Dashboard\OfficeController;
use App\Http\Controllers\Dashboard\PartnerController;
use App\Http\Controllers\Dashboard\PartnerTypeController;
use App\Http\Controllers\Dashboard\ProductController;
use App\Http\Controllers\Dashboard\ProductTypeController;
use App\Http\Controllers\Dashboard\RevenueTypeController;
use App\Http\Controllers\Dashboard\StateController;
use App\Http\Controllers\Dashboard\StatusController;
use App\Http\Controllers\Dashboard\TaskController;
use App\Http\Controllers\Dashboard\WorkflowController;
use App\Http\Controllers\User\CompanySettingController;
use App\Http\Controllers\User\RoleController;
use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::group(['middleware' => ['auth']], function() {

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::post('status-search',[ StatusController::class ,'search'])->name('status.search');
    Route::resource('status',StatusController::class)->except('create','edit','show');

    Route::post('branch-search',[ BranchController::class ,'search'])->name('branch.search');
    Route::resource('branch',BranchController::class)->except('create','edit','show');

    Route::post('appointment-search',[ AppointmentController::class ,'search'])->name('appointment.search');
    Route::resource('appointment',AppointmentController::class)->except('create','edit','show');

    Route::post('contact-search',[ ContactController::class ,'search'])->name('contact.search');
Route::resource('contact',ContactController::class)->except('create','edit','show');

    Route::post('workflow-search',[ WorkflowController::class ,'search'])->name('workflow.search');
    Route::resource('workflow',WorkflowController::class)->except('create','edit','show');

    Route::post('application-search',[ ApplicationController::class ,'search'])->name('application.search');
    Route::get('application/{id}',[ApplicationController::class,'index'])->name('application.index');
    Route::resource('application',ApplicationController::class)->except('index','create');


    Route::post('revenue-type-search',[ RevenueTypeController::class ,'search'])->name('revenueType.search');
    Route::resource('revenue-type',RevenueTypeController::class)
        ->name('index','revenueType.index')
        ->name('store','revenueType.store')
        ->name('update','revenueType.update')
        ->name('destroy','revenueType.destroy')
        ->except('create','edit','show');

    Route::post('product-type-search',[ ProductTypeController::class ,'search'])->name('productType.search');
    Route::resource('product-type',ProductTypeController::class)
        ->name('index','productType.index')
        ->name('store','productType.store')
        ->name('update','productType.update')
        ->name('destroy','productType.destroy')
        ->except('create','edit','show');

    Route::post('product-search',[ ProductController::class ,'search'])->name('product.search');
    Route::resource('product',ProductController::class)->except('create','edit','show');

    Route::post('partner-type-search',[ PartnerTypeController::class ,'search'])->name('partnerType.search');
    Route::resource('partner-type',PartnerTypeController::class)
        ->name('index','partnerType.index')
        ->name('store','partnerType.store')
        ->name('update','partnerType.update')
        ->name('destroy','partnerType.destroy')
        ->except('create','edit','show');

    Route::post('partner-search',[ PartnerController::class ,'search'])->name('partner.search');
    Route::resource('partner',PartnerController::class)->except('create','edit','show');

    Route::post('category-search',[ CategoryController::class ,'search'])->name('category.search');
    Route::resource('category',CategoryController::class)->except('create','edit','show');

    Route::post('enqury-search',[ EnquryController::class ,'search'])->name('enqury.search');
    Route::resource('enqury',EnquryController::class)->except('create','edit','show');

    Route::post('country-search',[ CountryController::class ,'search'])->name('country.search');
    Route::resource('country',CountryController::class)->except('create','edit','show');

    Route::post('state-search',[ StateController::class ,'search'])->name('state.search');
    Route::resource('state',StateController::class)->except('create','edit','show');

    Route::post('city-search',[ CityController::class ,'search'])->name('city.search');
    Route::resource('city',CityController::class)->except('create','edit','show');

    Route::post('client-search',[ ClientController::class ,'search'])->name('client.search');
    Route::resource('client',ClientController::class)->except('create','edit','show');

    Route::post('task-search',[ TaskController::class ,'search'])->name('task.search');
    Route::resource('task',TaskController::class)->except('create','edit','show');

    Route::post('agent-search',[ AgentController::class ,'search'])->name('agent.search');
    Route::resource('agent',AgentController::class)->except('create','edit','show');

    Route::post('office-search',[ OfficeController::class ,'search'])->name('office.search');
    Route::resource('office',OfficeController::class)->except('create','edit','show');

    Route::post('officeCheckin-search',[ OfficeCheckinController::class ,'search'])->name('officeCheckin.search');
    Route::resource('officeCheckin',OfficeCheckinController::class)->except('create','edit','show');


//    User Management
    Route::resource('roles', RoleController::class);
    Route::resource('user', UserController::class);
    Route::get('settings/company-settings', [CompanySettingController::class, 'editCompanySetting'])->name('company.edit');
    Route::post('settings/company-setting', [CompanySettingController::class, 'updateCompanySetting'])->name('company.update');
});

Route::get('migrate',function(){
    Artisan::call('migrate');
    dd('done');
});

 Route::get('migrate-fresh',function(){
     Artisan::call('migrate:fresh --seed');
     dd('done');
 });

Route::get('optimize',function(){
    Artisan::call('optimize');
    Artisan::call('optimize:clear');
    dd('done');
});

Route::get('seed',function(){
    Artisan::call('db:seed', [
        '--class' => CountrySeeder::class
    ]);
});

Route::get('rollback',function(){
    Artisan::call('migrate:rollback --step=3');
    dd('done');
});

Route::get('storage-link',function(){
    Artisan::call('storage:link');
    dd('done');
});

// Route::get('drop',function(){
//     Schema::dropIfExists('contacts');
//     dd('done');
// });

require __DIR__.'/auth.php';

app/Models/Dashboard/Agent.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{
    use HasFactory;

    protected $fillable = [
      'name',
      'agent_type',
      'agent_structure',
      'image',
      'phone',
      'email',
      'street',
      'city_id',
      'office_id',
    ];


    public function city(){
        return $this->belongsTo(City::class);
    }

    public function office(){
        return $this->belongsTo(Office::class);
    }
}

app/Models/Dashboard/Application.php
<?php

namespace App\Models\Dashboard;

use App\Models\User\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    use HasFactory;

    protected $fillable = [
      'client_id',
      'workflow_id',
      'partner_id',
      'branch_id',
      'product_id',
      'started_at',
      'ended_at',
      'applied_intake',
      'note_title',
      'note_description',
      'assignee_id',
      'application_form_id',
    ];

    public function client(){
        return $this->belongsTo(Client::class);
    }

    public function product(){
        return $this->belongsTo(Product::class);
    }

    public function branch(){
        return $this->belongsTo(Branch::class);
    }

    public function workflow(){
        return $this->belongsTo(Workflow::class);
    }

    public function assignee(){
        return $this->belongsTo(User::class,'assignee_id');
    }
}

app/Models/Dashboard/Appointment.php
<?php

namespace App\Models\Dashboard;

use App\Models\User\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    use HasFactory;

    protected $fillable = [
        'related_id',
        'user_id',
        'client_id',
        'timezone_id',
        'date',
        'time',
        'title',
        'description',
        'invitees_id',
    ];

    public function client(){
        return $this->belongsTo(Client::class);
    }

    public function timezone(){
        return $this->belongsTo(TimeZone::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Models/Dashboard/Branch.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'phone',
        'street',
        'city_id',
    ];

    public function city(){
        return $this->belongsTo(City::class);
    }

    public function partners(){
        return $this->hasMany(Partner::class);
    }

    public function products(){
        return $this->hasMany(Product::class);
    }

    public function applications(){
        return $this->hasMany(Application::class);
    }
}

app/Models/Dashboard/Category.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = [
        'name'
    ];
}

app/Models/Dashboard/City.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'state_id',
    ];


    public function state(){
        return $this->belongsTo(State::class);
    }
    public function agents(){
        return $this->hasMany(Agent::class);
    }
    public function branches(){
        return $this->hasMany(Branch::class);
    }
    public function offices(){
        return $this->hasMany(Office::class);
    }

    public function clients(){
        return $this->hasMany(Client::class);
    }

    public function partners(){
        return $this->hasMany(Partner::class);
    }

}

app/Models/Dashboard/Client.php
<?php

namespace App\Models\Dashboard;

use App\Models\User\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

     protected $fillable=[
         'image',
         'first_name',
         'last_name',
         'dob',
         'client_id',
         'email',
         'phone',
         'contact_reference',
         'street',
         'city_id',
         'zip_code',
         'visa_expiry_date',
         'application',
         'assignee_id',
         'followers',
         'source',
         'tag_name',
         'rating',
     ];

     public function user(){
         return $this->belongsTo(User::class,'id','assignee_id');
     }

    public function city(){
        return $this->belongsTo(City::class);
    }

    public function applications(){
        return $this->hasMany(Application::class);
    }

}

app/Models/Dashboard/Contact.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;

    protected $fillable = [
        'image',
        'name',
        'dob',
        'email',
        'phone',
        'street',
        'city_id',
        'zip_code',
    ];
}

app/Models/Dashboard/Country.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
    protected $fillable = [
        'code',
        'name',
        'phonecode'
    ];

    public function states(){
        return $this->hasMany(State::class);
    }
}

app/Models/Dashboard/Currency.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'code',
        'symbol',
    ];
}

app/Models/Dashboard/Document.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;
    protected $fillable = [
      'url',
      'application_id',
    ];
}

app/Models/Dashboard/Email.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Email extends Model
{
    use HasFactory;
    protected $fillable = [
      'from',
      'to',
      'subject',
      'message',
      'application_id',
    ];
}

app/Models/Dashboard/Enqury.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Enqury extends Model
{
    use HasFactory;
    protected $fillable = [
      'name',
      'email',
      'mobile',
      'higher_level_education',
      'comment',
    ];
}

app/Models/Dashboard/Fee.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fee extends Model
{
    use HasFactory;
    protected $fillable =  [
      'name',
      'amount',
      'commission',
      'payment_schedule_id',
    ];
}

app/Models/Dashboard/Office.php
<?php

namespace App\Models\Dashboard;

use App\Models\User\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Office extends Model
{
    use HasFactory;

    protected $fillable = [
      'name',
      'street',
      'city_id',
      'zip_code',
      'email',
      'phone',
      'mobile',
      'contact_person_id',
      'admin_id',
    ];

    public function agents(){
        return $this->hasMany(Agent::class);
    }


    public function admin(){
        return $this->belongsTo(User::class,'admin_id');
    }

    public function city(){
        return $this->belongsTo(City::class);
    }

    public function contactPerson(){
        return $this->belongsTo(User::class,'contact_person_id','id');
    }
}

app/Models/Dashboard/OfficeCheckin.php
<?php

namespace App\Models\Dashboard;

use App\Models\User\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OfficeCheckin extends Model
{
    use HasFactory;

    protected $fillable =[
        'date',
        'start',
        'wait_time',
        'contact_id',
        'visit_purpose',
        'assignee_id',
        'status'
    ];

    public function assignee(){
        return $this->belongsTo(User::class,'assignee_id');
    }

    public function contact(){
        return $this->belongsTo(Contact::class);
    }

}

app/Models/Dashboard/Partner.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    use HasFactory;

    protected $fillable = [
      'image',
      'master_category_id',
      'partner_type_id',
      'name',
      'partner_id',
      'business_registration_number',
      'service_workflow_id',
      'currency_id',
      'street',
      'zip_code',
      'city_id',
      'phone',
      'email',
      'fax',
      'website',
      'branch_id',
    ];


    public function partnerType(){
        return $this->belongsTo(PartnerType::class);
    }

    public function currency(){
        return $this->belongsTo(Currency::class);
    }

    public function city(){
        return $this->belongsTo(City::class);
    }

    public function branch(){
        return $this->belongsTo(Branch::class);
    }

    public function products(){
        return $this->hasMany(Product::class);
    }
}

resources/views/dashboard/partner/form.blade.php
<div class="row mb-2">
    <div class="col-6">
        <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }} mb-3">
            {{ Form::label('image', 'Image', ['class' => 'col-sm-3 control-label']) }}
            <div class="col-sm-9">
                {{ Form::file('image', ['class' => 'filestyle','id'=>'imageUpload']) }}
                {{-- <p class="help-block">Help block text</p> --}}
                <small class="text-danger">{{ $errors->first('image') }}</small>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div id="preview-wrap">
            <img src="{{ $partner->image ?? null }}" class="rounded" width="100px" id="imagePP">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-6">
        <div class="form-group{{ $errors->has('master_category_id') ? ' has-error' : '' }} mb-3">
            {{ Form::label('master_category_id', 'Master Category', ['class' => 'col-sm-6 control-label']) }}
            <div class="col-sm-9">
                {{ Form::select('master_category_id', $categories, null, ['class' => 'form-control select2', 'style'=>'width: 100%', 'onClick'=>'fetchStates()', 'required' => 'required']) }}
                <small class="text-danger">{{ $errors->first('master_category_id') }}</small>

            </div>
        </div>
    </div>

    <div class="col-6">
        <div class="form-group{{ $errors->has('partner_type_id') ? ' has-error' : '' }} mb-3">
            {{ Form::label('partner_type_id', 'Partner Type', ['class' => 'col-sm-6 control-label']) }}
            <div class="row">
                <div class="col-sm-9">
                    {{ Form::select('partner_type_id', $partnerTypes, null, ['class' => 'form-control select2','style'=>'width: 100%',  'id'=>'partner_type_id', 'required' => 'required']) }}
                    <small class="text-danger">{{ $errors->first('partner_type_id') }}</small>

                </div>
                <div class="col-sm-3">
                    <a href="{{route('partnerType.index')}}" class="btn btn-primary"><i class="mdi mdi-plus"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-6">
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} mb-3">
            {{ Form::label('name', 'Name', ['class' => 'col-sm-6 control-label','for'=>'name']) }}
            <div class="col-sm-9">
                {{ Form::text('name', null, ['class' => 'form-control','placeholder' => 'Enter name','id'=>'name', 'required']) }}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group{{ $errors->has('business_registration_number') ? ' has-error' : '' }} mb-3">
            {{ Form::label('business_registration_number', 'Business Registration Number', ['class' => 'col-sm-12 control-label','for'=>'business_registration_number']) }}
            <div class="col-sm-9">
                {{ Form::text('business_registration_number', null, ['class' => 'form-control','placeholder' => 'Enter business_registration_number','id'=>'business_registration_number', 'required']) }}
                <small class="text-danger">{{ $errors->first('business_registration_number') }}</small>
            </div>
        </div>
    </div>

</div>
<div class="row">
    <div class="col-6">
        <div class="form-group{{ $errors->has('service_workflow_id') ? ' has-error' : '' }} mb-3">
            {{ Form::label('service_workflow_id', 'Service Workflow', ['class' => 'col-sm-6 control-label']) }}
            <div class="col-sm-9">
                {{ Form::select('service_workflow_id', $serviceWorkflows, null, ['class' => 'form-control select2', 'style'=>'width: 100%', 'onClick'=>'fetchStates()', 'required' => 'required']) }}
                <small class="text-danger">{{ $errors->first('service_workflow_id') }}</small>

            </div>
        </div>
    </div>

    <div class="col-6">
        <div class="form-group{{ $errors->has('currency_id') ? ' has-error' : '' }} mb-3">
            {{ Form::label('currency_id', 'Currency', ['class' => 'col-sm-6 control-label']) }}
            <div class="col-sm-9">
                {{ Form::select('currency_id', $currencies, null, ['class' => 'form-control select2','style'=>'width: 100%',  'id'=>'currency_id', 'required' => 'required']) }}
                <small class="text-danger">{{ $errors->first('currency_id') }}</small>

            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-6">
        <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }} mb-3">
            {{ Form::label('phone', 'Phone', ['class' => 'col-sm-6 control-label','for'=>'phone']) }}
            <div class="col-sm-9">
                {{ Form::text('phone', null, ['class' => 'form-control','placeholder' => 'Enter phone','id'=>'phone', 'required']) }}
                <small class="text-danger">{{ $errors->first('phone') }}</small>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }} mb-3">
            {{ Form::label('email', 'Email', ['class' => 'col-sm-6 control-label','for'=>'email']) }}
            <div class="col-sm-9">
                {{ Form::text('email', null, ['class' => 'form-control','placeholder' => 'Enter email','id'=>'email', 'required']) }}
                <small class="text-danger">{{ $errors->first('email') }}</small>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-6">
        <div class="form-group{{ $errors->has('fax') ? ' has-error' : '' }} mb-3">
            {{ Form::label('fax', 'Fax', ['class' => 'col-sm-6 control-label','for'=>'fax']) }}
            <div class="col-sm-9">
                {{ Form::text('fax', null, ['class' => 'form-control','placeholder' => 'Enter fax','id'=>'fax', 'required']) }}
                <small class="text-danger">{{ $errors->first('fax') }}</small>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group{{ $errors->has('website') ? ' has-error' : '' }} mb-3">
            {{ Form::label('website', 'Website', ['class' => 'col-sm-6 control-label','for'=>'website']) }}
            <div class="col-sm-9">
                {{ Form::text('website', null, ['class' => 'form-control','placeholder' => 'Enter website','id'=>'website', 'required']) }}
                <small class="text-danger">{{ $errors->first('website') }}</small>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <div class="form-group{{ $errors->has('country_id') ? ' has-error' : '' }} mb-3">
            {{ Form::label('country_id', 'Country', ['class' => 'col-sm-6 control-label']) }}
            <div class="col-sm-9">
                {{ Form::select('country_id', $countries, null, ['class' => 'form-control select2', 'style'=>'width: 100%', 'onClick'=>'fetchStates()', 'required' => 'required']) }}
                <small class="text-danger">{{ $errors->first('country_id') }}</small>

            </div>
        </div>
    </div>

    <div class="col-6">
        <div class="form-group{{ $errors->has('state_id') ? ' has-error' : '' }} mb-3">
            {{ Form::label('state_id', 'State', ['class' => 'col-sm-6 control-label']) }}
            <div class="col-sm-9">
                {{ Form::select('state_id', [], null, ['class' => 'form-control select2','style'=>'width: 100%',  'id'=>'state_id', 'required' => 'required']) }}
                <small class="text-danger">{{ $errors->first('state_id') }}</small>

            </div>
        </div>
    </div>
</div>


<div class="row">

    <div class="col-6">
        <div class="form-group{{ $errors->has('city_id') ? ' has-error' : '' }} mb-3">
            {{ Form::label('city_id', 'City', ['class' => 'col-sm-6 control-label']) }}
            <div class="col-sm-9">
                {{ Form::select('city_id', [], null, ['class' => 'form-control select2', 'style'=>'width: 100%', 'id'=>'city_id',  'required' => 'required']) }}
                <small class="text-danger">{{ $errors->first('city_id') }}</small>

            </div>
        </div>
    </div>

    <div class="col-6">
        <div class="form-group{{ $errors->has('street') ? ' has-error' : '' }} mb-3">
            {{ Form::label('street', 'Street', ['class' => 'col-sm-6 control-label','for'=>'street']) }}
            <div class="col-sm-9">
                {{ Form::text('street', null, ['class' => 'form-control','placeholder' => 'Enter street','id'=>'street', 'required']) }}
                <small class="text-danger">{{ $errors->first('street') }}</small>
            </div>
        </div>
    </div>

</div>


<div class="row">
    <div class="col-6">
        <div class="form-group{{ $errors->has('zip_code') ? ' has-error' : '' }} mb-3">
            {{ Form::label('zip_code', 'Zip Code', ['class' => 'col-sm-6 control-label','for'=>'zip_code']) }}
            <div class="col-sm-9">
                {{ Form::text('zip_code', null, ['class' => 'form-control','placeholder' => 'Enter zip_code','id'=>'zip_code', 'required']) }}
                <small class="text-danger">{{ $errors->first('zip_code') }}</small>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group{{ $errors->has('branch_id') ? ' has-error' : '' }} mb-3">
            {{ Form::label('branch_id', 'Branch', ['class' => 'col-sm-6 control-label']) }}

            <div class="row">
                <div class="col-sm-9">
                    {{ Form::select('branch_id', $branches, null, ['class' => 'form-control select2','style'=>'width: 100%',  'id'=>'branch_id', 'required' => 'required']) }}
                    <small class="text-danger">{{ $errors->first('branch_id') }}</small>
                </div>
                <div class="col-sm-3">
                    <a href="{{route('branch.index')}}" class="btn btn-primary"><i class="mdi mdi-plus"></i></a>
                </div>
            </div>
        </div>
    </div>

</div>

resources/views/dashboard/partner/partnerTable.blade.php
<table id="datatable" class="table table-striped table-bordered dt-responsive nowrap">
    <thead>
        <tr>
            <th>{{ __('ID')}}</th>
            <th>{{ __('Name') }}</th>
            <th>{{ __('Number') }}</th>
            <th>{{ __('Email') }}</th>
            <th class="action">{{ __('Action') }}</th>
        </tr>
    </thead>
    <tbody>
    @foreach ($partners as $partner)
        <tr>
            <td>{{ $partner->sl}}</td>
            <td>{{ $partner->name }}</td>
            <td>{{ $partner->phone}}</td>
            <td>{{ $partner->email}}</td>
            <td nowrap="nowrap">
                {{-- <a class="btn btn-info" href="{{ route('partner.show', $partner->id) }}"><i class="fas fa-eye"></i></a> --}}
                {{-- Edit Modal --}}
                <button onclick="editData(this)" type="button" class="btn btn-primary btn-md waves-effect waves-light"
                        data-bs-toggle="modal" data-bs-target="#edit{{$partner->id}}"><i
                        class="fas fa-edit"></i></button>
                <!-- sample modal content -->
                <div id="edit{{$partner->id}}" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
                     aria-labelledby="editLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="editLabel">Edit Status</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            {{ Form::model($partner, ['route' => ['partner.update', $partner->id], 'method' => 'PUT', 'class' => 'needs-validation', 'novalidate']) }}
                            <div class="modal-body">
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                @include('dashboard.partner.form')
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary waves-effect"
                                        data-bs-dismiss="modal">Close</button>
                                <button type="submit"
                                        class="btn btn-primary waves-effect waves-light">Update</button>
                            </div>
                            {{ Form::close() }}
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
                {{ Form::open(['method' => 'DELETE', 'route' => ['partner.destroy', $partner->id], 'style' => 'display:inline']) }}
                {{ Form::button('<i class="fas fa-trash"  aria-hidden="true"></i>', ['class' => 'btn btn-danger btm-md', 'type' => 'submit']) }}
                {{ Form::close() }}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>